{{- define "libapp.ingress.tpl" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # name: 支持通过 .Values.ingress.name 覆盖，默认使用 fullname + -tls-ingress
  name: {{ default (printf "%s-tls-ingress" (include "libapp.fullname" .))}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "libapp.name" . }}
    release: {{ .Release.Name }}
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":11000}]'
spec:
  ingressClassName: {{ default "alb" .Values.ingress.class }}
  rules:
  - host: {{ default (printf "%s.example.com" (include "libapp.fullname" .)) .Values.ingress.hostname | quote }}
    http:
      paths:
        {{- $atapp := (default (dict) .Values.atapp) -}}
        {{- $deploy := (default (dict) $atapp.deployment) -}}
        {{- $env := (default "" $deploy.deployment_environment) -}}
        {{- $ws := (default (dict) .Values.websocket) -}}
        {{- $wspath := (default "" $ws.path) -}}
      - path: {{ printf "/%s/%s/ws/v1" $env $wspath | replace "///" "/" | replace "//" "/" | quote }}
        backend:
          service: 
            name: {{ default "project-y-tls-gateway" .Values.httproute.parentRefsName | quote }}
            port:
              number: {{ default 443 .Values.ingress.port }}
        pathType: Prefix
{{- end -}}
{{- define "libapp.ingress" -}}
{{- template "libapp.util.merge" (append . "libapp.ingress.tpl") -}}
{{- end -}}
