// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: protocol/pbdesc/sample.proto

package main

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleNested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedId      int64                  `protobuf:"varint,1,opt,name=nested_id,json=nestedId,proto3" json:"nested_id,omitempty"`
	NestedName    string                 `protobuf:"bytes,2,opt,name=nested_name,json=nestedName,proto3" json:"nested_name,omitempty"`
	NestedData    []byte                 `protobuf:"bytes,3,opt,name=nested_data,json=nestedData,proto3" json:"nested_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleNested) Reset() {
	*x = SampleNested{}
	mi := &file_protocol_pbdesc_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleNested) ProtoMessage() {}

func (x *SampleNested) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pbdesc_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleNested.ProtoReflect.Descriptor instead.
func (*SampleNested) Descriptor() ([]byte, []int) {
	return file_protocol_pbdesc_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleNested) GetNestedId() int64 {
	if x != nil {
		return x.NestedId
	}
	return 0
}

func (x *SampleNested) GetNestedName() string {
	if x != nil {
		return x.NestedName
	}
	return ""
}

func (x *SampleNested) GetNestedData() []byte {
	if x != nil {
		return x.NestedData
	}
	return nil
}

type SampleContainer struct {
	state      protoimpl.MessageState   `protogen:"open.v1"`
	Id         int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string                   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Nested     *SampleNested            `protobuf:"bytes,3,opt,name=nested,proto3" json:"nested,omitempty"`
	NestedList []*SampleNested          `protobuf:"bytes,4,rep,name=nested_list,json=nestedList,proto3" json:"nested_list,omitempty"`
	NestedMap  map[string]*SampleNested `protobuf:"bytes,5,rep,name=nested_map,json=nestedMap,proto3" json:"nested_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload    []byte                   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Labels     []string                 `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	// Types that are valid to be assigned to OptionalValue:
	//
	//	*SampleContainer_OptInt
	//	*SampleContainer_OptNested
	OptionalValue isSampleContainer_OptionalValue `protobuf_oneof:"optional_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleContainer) Reset() {
	*x = SampleContainer{}
	mi := &file_protocol_pbdesc_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleContainer) ProtoMessage() {}

func (x *SampleContainer) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pbdesc_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleContainer.ProtoReflect.Descriptor instead.
func (*SampleContainer) Descriptor() ([]byte, []int) {
	return file_protocol_pbdesc_sample_proto_rawDescGZIP(), []int{1}
}

func (x *SampleContainer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SampleContainer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SampleContainer) GetNested() *SampleNested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *SampleContainer) GetNestedList() []*SampleNested {
	if x != nil {
		return x.NestedList
	}
	return nil
}

func (x *SampleContainer) GetNestedMap() map[string]*SampleNested {
	if x != nil {
		return x.NestedMap
	}
	return nil
}

func (x *SampleContainer) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SampleContainer) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SampleContainer) GetOptionalValue() isSampleContainer_OptionalValue {
	if x != nil {
		return x.OptionalValue
	}
	return nil
}

func (x *SampleContainer) GetOptInt() int32 {
	if x != nil {
		if x, ok := x.OptionalValue.(*SampleContainer_OptInt); ok {
			return x.OptInt
		}
	}
	return 0
}

func (x *SampleContainer) GetOptNested() *SampleNested {
	if x != nil {
		if x, ok := x.OptionalValue.(*SampleContainer_OptNested); ok {
			return x.OptNested
		}
	}
	return nil
}

type isSampleContainer_OptionalValue interface {
	isSampleContainer_OptionalValue()
}

type SampleContainer_OptInt struct {
	OptInt int32 `protobuf:"varint,8,opt,name=opt_int,json=optInt,proto3,oneof"`
}

type SampleContainer_OptNested struct {
	OptNested *SampleNested `protobuf:"bytes,9,opt,name=opt_nested,json=optNested,proto3,oneof"`
}

func (*SampleContainer_OptInt) isSampleContainer_OptionalValue() {}

func (*SampleContainer_OptNested) isSampleContainer_OptionalValue() {}

var File_protocol_pbdesc_sample_proto protoreflect.FileDescriptor

const file_protocol_pbdesc_sample_proto_rawDesc = "" +
	"\n" +
	"\x1cprotocol/pbdesc/sample.proto\"m\n" +
	"\fSampleNested\x12\x1b\n" +
	"\tnested_id\x18\x01 \x01(\x03R\bnestedId\x12\x1f\n" +
	"\vnested_name\x18\x02 \x01(\tR\n" +
	"nestedName\x12\x1f\n" +
	"\vnested_data\x18\x03 \x01(\fR\n" +
	"nestedData\"\xaa\x03\n" +
	"\x0fSampleContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x06nested\x18\x03 \x01(\v2\r.SampleNestedR\x06nested\x12.\n" +
	"\vnested_list\x18\x04 \x03(\v2\r.SampleNestedR\n" +
	"nestedList\x12>\n" +
	"\n" +
	"nested_map\x18\x05 \x03(\v2\x1f.SampleContainer.NestedMapEntryR\tnestedMap\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x16\n" +
	"\x06labels\x18\a \x03(\tR\x06labels\x12\x19\n" +
	"\aopt_int\x18\b \x01(\x05H\x00R\x06optInt\x12.\n" +
	"\n" +
	"opt_nested\x18\t \x01(\v2\r.SampleNestedH\x00R\toptNested\x1aK\n" +
	"\x0eNestedMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.SampleNestedR\x05value:\x028\x01B\x10\n" +
	"\x0eoptional_valueB\\H\x01ZRgithub.com/atframework/atsf4g-go/service-lobbysvr/protocol/private/protocol/pbdesc\x80\x01\x01\xf8\x01\x01b\x06proto3"

var (
	file_protocol_pbdesc_sample_proto_rawDescOnce sync.Once
	file_protocol_pbdesc_sample_proto_rawDescData []byte
)

func file_protocol_pbdesc_sample_proto_rawDescGZIP() []byte {
	file_protocol_pbdesc_sample_proto_rawDescOnce.Do(func() {
		file_protocol_pbdesc_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_pbdesc_sample_proto_rawDesc), len(file_protocol_pbdesc_sample_proto_rawDesc)))
	})
	return file_protocol_pbdesc_sample_proto_rawDescData
}

var file_protocol_pbdesc_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_pbdesc_sample_proto_goTypes = []any{
	(*SampleNested)(nil),    // 0: SampleNested
	(*SampleContainer)(nil), // 1: SampleContainer
	nil,                     // 2: SampleContainer.NestedMapEntry
}
var file_protocol_pbdesc_sample_proto_depIdxs = []int32{
	0, // 0: SampleContainer.nested:type_name -> SampleNested
	0, // 1: SampleContainer.nested_list:type_name -> SampleNested
	2, // 2: SampleContainer.nested_map:type_name -> SampleContainer.NestedMapEntry
	0, // 3: SampleContainer.opt_nested:type_name -> SampleNested
	0, // 4: SampleContainer.NestedMapEntry.value:type_name -> SampleNested
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_pbdesc_sample_proto_init() }
func file_protocol_pbdesc_sample_proto_init() {
	if File_protocol_pbdesc_sample_proto != nil {
		return
	}
	file_protocol_pbdesc_sample_proto_msgTypes[1].OneofWrappers = []any{
		(*SampleContainer_OptInt)(nil),
		(*SampleContainer_OptNested)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_pbdesc_sample_proto_rawDesc), len(file_protocol_pbdesc_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_pbdesc_sample_proto_goTypes,
		DependencyIndexes: file_protocol_pbdesc_sample_proto_depIdxs,
		MessageInfos:      file_protocol_pbdesc_sample_proto_msgTypes,
	}.Build()
	File_protocol_pbdesc_sample_proto = out.File
	file_protocol_pbdesc_sample_proto_goTypes = nil
	file_protocol_pbdesc_sample_proto_depIdxs = nil
}
