// Code generated by protoc-gen-mutable. DO NOT EDIT.
// source: protocol/pbdesc/sample.proto

package main

import (
	"log/slog"

	"google.golang.org/protobuf/proto"

	"reflect"

	pu "github.com/atframework/atframe-utils-go/proto_utility"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

type innerFile_protocol_pbdesc_sample_protoReadonlyMessage interface {
	Descriptor() protoreflect.MessageDescriptor
	Type() protoreflect.MessageType
	New() protoreflect.Message
	Interface() protoreflect.ProtoMessage
	Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool)
	Has(protoreflect.FieldDescriptor) bool
	Get(protoreflect.FieldDescriptor) protoreflect.Value
	WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor
	GetUnknown() protoreflect.RawFields
	IsValid() bool
}

// ===== Clone methods for SampleNested ===== Message ====
func (m *SampleNested) Clone() *SampleNested {
	if m == nil {
		return new(SampleNested)
	}
	return proto.Clone(m).(*SampleNested)
}

// ===== Merge methods for SampleNested ===== Message ====
func (m *SampleNested) Merge(src *SampleNested) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for SampleNested ===== Message ====
func (m *SampleNested) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableText(m))
}

// ===== GetMessageReflectType methods for SampleNested ===== Message =====
var reflectTypeSampleNested reflect.Type

func GetReflectTypeSampleNested() reflect.Type {
	return reflectTypeSampleNested
}

// ===== Readonly wrapper for SampleNested ===== Message ====
type Readonly_SampleNested struct {
	protoData       *SampleNested
	fieldNestedId   int64
	fieldNestedName string
	fieldNestedData []byte
}

func (r *Readonly_SampleNested) ReadonlyProtoReflect() innerFile_protocol_pbdesc_sample_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *SampleNested) ToReadonly() *Readonly_SampleNested {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_SampleNested{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_SampleNested) CloneMessage() *SampleNested {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.Clone()
}

func (r *Readonly_SampleNested) ToMessage() *SampleNested {
	return r.CloneMessage()
}

func (r *Readonly_SampleNested) initFromProto(src *SampleNested) {
	if r == nil || src == nil {
		return
	}
	r.fieldNestedId = src.GetNestedId()
	r.fieldNestedName = src.GetNestedName()
	if v := src.GetNestedData(); len(v) != 0 {
		r.fieldNestedData = append([]byte(nil), v...)
	} else {
		r.fieldNestedData = nil
	}
}

func (r *Readonly_SampleNested) GetNestedId() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldNestedId
}

func (r *Readonly_SampleNested) GetNestedName() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldNestedName
}

func (r *Readonly_SampleNested) GetNestedData() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldNestedData) == 0 {
		return r.fieldNestedData
	}
	dup := make([]byte, len(r.fieldNestedData))
	copy(dup, r.fieldNestedData)
	return dup
}

// ===== Clone methods for SampleContainer ===== Message ====
func (m *SampleContainer) Clone() *SampleContainer {
	if m == nil {
		return new(SampleContainer)
	}
	return proto.Clone(m).(*SampleContainer)
}

// ===== Merge methods for SampleContainer ===== Message ====
func (m *SampleContainer) Merge(src *SampleContainer) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for SampleContainer ===== Message ====
func (m *SampleContainer) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableText(m))
}

// ===== GetMessageReflectType methods for SampleContainer ===== Message =====
var reflectTypeSampleContainer reflect.Type

func GetReflectTypeSampleContainer() reflect.Type {
	return reflectTypeSampleContainer
}

// ===== Readonly wrapper for SampleContainer ===== Message ====
type Readonly_SampleContainer struct {
	protoData              *SampleContainer
	fieldId                int32
	fieldTitle             string
	fieldNested            *Readonly_SampleNested
	fieldNestedList        []*Readonly_SampleNested
	fieldNestedMap         map[string]*Readonly_SampleNested
	fieldPayload           []byte
	fieldLabels            []string
	fieldOptInt            int32
	fieldOptNested         *Readonly_SampleNested
	fieldOptionalValueCase SampleContainer_EnOptionalValueID
}

func (r *Readonly_SampleContainer) ReadonlyProtoReflect() innerFile_protocol_pbdesc_sample_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *SampleContainer) ToReadonly() *Readonly_SampleContainer {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_SampleContainer{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_SampleContainer) CloneMessage() *SampleContainer {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.Clone()
}

func (r *Readonly_SampleContainer) ToMessage() *SampleContainer {
	return r.CloneMessage()
}

func (r *Readonly_SampleContainer) initFromProto(src *SampleContainer) {
	if r == nil || src == nil {
		return
	}
	r.fieldId = src.GetId()
	r.fieldTitle = src.GetTitle()
	if v := src.GetNested(); v != nil {
		r.fieldNested = v.ToReadonly()
	} else {
		r.fieldNested = nil
	}
	if v := src.GetNestedList(); len(v) != 0 {
		out := make([]*Readonly_SampleNested, 0, len(v))
		for _, item := range v {
			if item == nil {
				out = append(out, nil)
				continue
			}
			out = append(out, item.ToReadonly())
		}
		r.fieldNestedList = out
	} else {
		r.fieldNestedList = nil
	}
	if v := src.GetNestedMap(); len(v) != 0 {
		copied := make(map[string]*Readonly_SampleNested, len(v))
		for mk, mv := range v {
			if mv == nil {
				copied[mk] = nil
				continue
			}
			copied[mk] = mv.ToReadonly()
		}
		r.fieldNestedMap = copied
	} else {
		r.fieldNestedMap = nil
	}
	if v := src.GetPayload(); len(v) != 0 {
		r.fieldPayload = append([]byte(nil), v...)
	} else {
		r.fieldPayload = nil
	}
	if v := src.GetLabels(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldLabels = copied
	} else {
		r.fieldLabels = nil
	}
	r.fieldOptInt = src.GetOptInt()
	if v := src.GetOptNested(); v != nil {
		r.fieldOptNested = v.ToReadonly()
	} else {
		r.fieldOptNested = nil
	}
}

func (r *Readonly_SampleContainer) GetId() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldId
}

func (r *Readonly_SampleContainer) GetTitle() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldTitle
}

func (r *Readonly_SampleContainer) GetNested() *Readonly_SampleNested {
	if r == nil {
		var zero *Readonly_SampleNested
		return zero
	}
	return r.fieldNested
}

func (r *Readonly_SampleContainer) GetNestedList() []*Readonly_SampleNested {
	if r == nil {
		var zero []*Readonly_SampleNested
		return zero
	}
	return r.fieldNestedList
}

func (r *Readonly_SampleContainer) GetNestedMap() map[string]*Readonly_SampleNested {
	if r == nil {
		var zero map[string]*Readonly_SampleNested
		return zero
	}
	return r.fieldNestedMap
}

func (r *Readonly_SampleContainer) GetPayload() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldPayload) == 0 {
		return r.fieldPayload
	}
	dup := make([]byte, len(r.fieldPayload))
	copy(dup, r.fieldPayload)
	return dup
}

func (r *Readonly_SampleContainer) GetLabels() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldLabels
}

func (r *Readonly_SampleContainer) GetOptInt() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldOptInt
}

func (r *Readonly_SampleContainer) GetOptNested() *Readonly_SampleNested {
	if r == nil {
		var zero *Readonly_SampleNested
		return zero
	}
	return r.fieldOptNested
}

func (r *Readonly_SampleContainer) GetOptionalValueOneofCase() SampleContainer_EnOptionalValueID {
	if r == nil {
		return 0
	}
	return r.protoData.GetOptionalValueOneofCase()
}

func (r *Readonly_SampleContainer) GetOptionalValueReflectType() reflect.Type {
	if r == nil {
		return nil
	}
	return r.protoData.GetOptionalValueReflectType()
}

// ===== Case Enum for SampleContainer Oneof OptionalValue ===== Oneof =====
type SampleContainer_EnOptionalValueID int32

const (
	SampleContainer_EnOptionalValueID_NONE      SampleContainer_EnOptionalValueID = 0 // none
	SampleContainer_EnOptionalValueID_OptInt    SampleContainer_EnOptionalValueID = 8 // opt_int
	SampleContainer_EnOptionalValueID_OptNested SampleContainer_EnOptionalValueID = 9 // opt_nested
)

// ===== GetCase interface for SampleContainer Oneof OptionalValue ===== Oneof =====
type getSampleContainer_OptionalValue interface {
	GetSampleContainer_OptionalValue() SampleContainer_EnOptionalValueID
	GetReflectTypeSampleContainer_OptionalValue() reflect.Type
}

// ===== GetCase methods for SampleContainer Oneof OptionalValue ===== Oneof =====
func (m *SampleContainer) GetOptionalValueOneofCase() SampleContainer_EnOptionalValueID {
	if m == nil {
		return 0
	}
	v, ok := m.OptionalValue.(getSampleContainer_OptionalValue)
	if !ok {
		return 0
	}
	return v.GetSampleContainer_OptionalValue()
}

// ===== GetOneofReflectType methods for SampleContainer Oneof OptionalValue ===== Oneof =====
func (m *SampleContainer) GetOptionalValueReflectType() reflect.Type {
	if m == nil {
		return nil
	}
	v, ok := m.OptionalValue.(getSampleContainer_OptionalValue)
	if !ok {
		return nil
	}
	return v.GetReflectTypeSampleContainer_OptionalValue()
}

// ===== Mutable methods for SampleContainer ===== Message =====
func (m *SampleContainer) MutableNested() *SampleNested {
	if m.Nested == nil {
		m.Nested = new(SampleNested)
	}
	return m.Nested
}

// ===== Mutable methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) MutableNestedList() []*SampleNested {
	if m.NestedList == nil {
		m.NestedList = []*SampleNested{}
	}
	return m.NestedList
}

// ===== ReverseIfNil methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) ReverseIfNilNestedList(l int32) []*SampleNested {
	if m.NestedList == nil {
		m.NestedList = make([]*SampleNested, 0, l)
	}
	return m.NestedList
}

// ===== Append methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) AppendNestedList(d *SampleNested) {
	if m.NestedList == nil {
		m.NestedList = []*SampleNested{}
	}
	m.NestedList = append(m.NestedList, d)
}

// ===== Add methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) AddNestedList() *SampleNested {
	if m.NestedList == nil {
		m.NestedList = []*SampleNested{}
	}
	addValue := new(SampleNested)
	m.NestedList = append(m.NestedList, addValue)
	return addValue
}

// ===== Merge methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) MergeNestedList(d []*SampleNested) []*SampleNested {
	if m.NestedList == nil {
		m.NestedList = []*SampleNested{}
	}
	m.NestedList = append(m.NestedList, d...)
	return m.NestedList
}

// ===== RemoveLast methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) RemoveLastNestedList() {
	if m.NestedList == nil {
		m.NestedList = []*SampleNested{}
	}
	if len(m.NestedList) != 0 {
		m.NestedList = m.NestedList[:len(m.NestedList)-1]
	}
}

// ===== Mutable methods for SampleContainer ===== Map =====
func (m *SampleContainer) MutableNestedMap() map[string]*SampleNested {
	if m.NestedMap == nil {
		m.NestedMap = make(map[string]*SampleNested, 0)
	}
	return m.NestedMap
}

// ===== Mutable methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) MutableLabels() []string {
	if m.Labels == nil {
		m.Labels = []string{}
	}
	return m.Labels
}

// ===== ReverseIfNil methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) ReverseIfNilLabels(l int32) []string {
	if m.Labels == nil {
		m.Labels = make([]string, 0, l)
	}
	return m.Labels
}

// ===== Append methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) AppendLabels(d string) {
	if m.Labels == nil {
		m.Labels = []string{}
	}
	m.Labels = append(m.Labels, d)
}

// ===== Merge methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) MergeLabels(d []string) []string {
	if m.Labels == nil {
		m.Labels = []string{}
	}
	m.Labels = append(m.Labels, d...)
	return m.Labels
}

// ===== RemoveLast methods for SampleContainer ===== Repeated =====
func (m *SampleContainer) RemoveLastLabels() {
	if m.Labels == nil {
		m.Labels = []string{}
	}
	if len(m.Labels) != 0 {
		m.Labels = m.Labels[:len(m.Labels)-1]
	}
}

// ===== Mutable methods for SampleContainer ===== Oneof =====
func (m *SampleContainer) MutableOptInt() *SampleContainer_OptInt {
	if x, ok := m.OptionalValue.(*SampleContainer_OptInt); ok {
		return x
	}
	x := new(SampleContainer_OptInt)
	m.OptionalValue = x
	return x
}

// ===== Get reflect Type for SampleContainer Oneof OptionalValue ===== Oneof =====
var reflectTypeSampleContainer_OptInt reflect.Type

func GetReflectTypeSampleContainer_OptInt() reflect.Type {
	return reflectTypeSampleContainer_OptInt
}

// ===== Oneof Interface for SampleContainer Oneof SampleContainer_OptInt ===== Oneof =====
func (m *SampleContainer_OptInt) GetSampleContainer_OptionalValue() SampleContainer_EnOptionalValueID {
	return SampleContainer_EnOptionalValueID_OptInt
}
func (m *SampleContainer_OptInt) GetReflectTypeSampleContainer_OptionalValue() reflect.Type {
	return reflectTypeSampleContainer_OptInt
}

// ===== Mutable methods for SampleContainer ===== Oneof =====
func (m *SampleContainer) MutableOptNested() *SampleContainer_OptNested {
	if x, ok := m.OptionalValue.(*SampleContainer_OptNested); ok {
		return x
	}
	x := new(SampleContainer_OptNested)
	m.OptionalValue = x
	return x
}

// ===== Get reflect Type for SampleContainer Oneof OptionalValue ===== Oneof =====
var reflectTypeSampleContainer_OptNested reflect.Type

func GetReflectTypeSampleContainer_OptNested() reflect.Type {
	return reflectTypeSampleContainer_OptNested
}

// ===== Oneof Interface for SampleContainer Oneof SampleContainer_OptNested ===== Oneof =====
func (m *SampleContainer_OptNested) GetSampleContainer_OptionalValue() SampleContainer_EnOptionalValueID {
	return SampleContainer_EnOptionalValueID_OptNested
}
func (m *SampleContainer_OptNested) GetReflectTypeSampleContainer_OptionalValue() reflect.Type {
	return reflectTypeSampleContainer_OptNested
}

func init() {
	reflectTypeSampleNested = reflect.TypeOf((*SampleNested)(nil)).Elem()
	reflectTypeSampleContainer = reflect.TypeOf((*SampleContainer)(nil)).Elem()
	reflectTypeSampleContainer_OptInt = reflect.TypeOf((*SampleContainer_OptInt)(nil)).Elem()
	reflectTypeSampleContainer_OptNested = reflect.TypeOf((*SampleContainer_OptNested)(nil)).Elem()
}
